<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Sso
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div style="text-align: center;padding:13px;margin:auto;width:35%">
    <a href="<?php echo Mage::getUrl('sso/sso/auth'); ?>">
        <button name="authorization" value="true" style="width:146px;height: 40px;float:left;">Authorize</button>
    </a>
    <a href="<?php echo Mage::getUrl('sso/sso/cancel'); ?>"><button name="cancel" value="true" style="width:146px;height: 40px;float:right;"> 
        Cancel</button>
    </a>
</div>