<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Sso
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div style="text-align: center;padding:13px;margin:auto;width:35%">
    <button onclick="wkSsoAction(this)" name="authorization" data-action="<?php echo Mage::getUrl('sso/sso/auth'); ?>" value="true" style="width:146px;height: 40px;float:left;">Authorize</button>
    <button onclick="wkSsoAction(this)" name="cancel" data-action="<?php echo Mage::getUrl('sso/sso/cancel'); ?>" value="true" style="width:146px;height: 40px;float:right;"> 
        Cancel</button>
</div>
<script>
    function wkSsoAction(button){
        var url=button.getAttribute("data-action");
        window.location.replace(url);
    }
</script>