<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Sso
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div style="padding:13px;margin:auto;width:50%">
<?php
if (Mage::getSingleton("core/session")->getSsoClientId()) {
    ?>
<div class="page-title">
    <h1>Login</h1>
</div>
<div class="webkul-sso">
    <form id="webkul-sso-loginform" name="sso_login" action= "<?php echo Mage::getUrl('sso/sso/login'); ?>" method="post"  enctype="multipart/form-data">
        <div class="fieldset">
            <h2 class="legend">Enter Credentials</h2>
            <p class="required">* Required Fields</p>
            <div class="field name-email">
                <label for="email" class="required"><em>*</em>Email</label>
                <div class="input-box">
                    <input type="text" id="email" name="email" title="Email" maxlength="255" class="input-text required-entry validate-email">
                </div>
            </div>

            <div class="field name-password">
                <label for="roll_no" class="required"><em>*</em>Password</label>
                <div class="input-box">
                    <input type="password" id="password" name="password" title="Password" maxlength="255" class="input-text required-entry">
                </div>
            </div>

            <div class="buttons-set">
                <button type="submit" title="Login" class="button"><span><span>Login</span></span></button>
            </div>
        </div>
    </form>
</div>
<?php

}
?>
</div>
<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('webkul-sso-loginform');
    //]]>
</script>